FROM golang:1.18-alpine as builder

ARG MONSTER_REACHER_SERVER_PATH

WORKDIR /app

RUN apk update && apk add git
RUN git clone https://github.com/Zmuo12345/monster-reacher-server.git

WORKDIR /app/monster-reacher-server/microservices/cmd/authentication

RUN go mod download
RUN go build .

EXPOSE 3000